:rotating_light: build: Introduces prettier
And fix the build, the error log was:
```
Run yarn install
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error @cspotcode/source-map-support@0.7.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```